import time
print("current time in second",time.time())
print("===============")
print("current time",time.ctime())
print("===============")
print("current time after 30 sec:",time.ctime(time.time()+30))
print("===============")
t=time.localtime()
print("time:",t)
print("===============")
print("current month",t.tm_mon)
print("current year",t.tm_year)
print("current day",t.tm_mday)
print("current hour",t.tm_hour)
print("current miniut",t.tm_min)
print("current second",t.tm_sec)
print("===============")
